spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ws_service"
    username: "mslim"
    password: "{cipher}b782b7d252d96a69b616427af9d0e9d689318d28d1ac6cbea4fb26e40233dee4"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update
      
logging:
  level:
    com.wsproject.wsservice: debug
    
custom:
  jwt-signkey: "{cipher}73e168f04e3f17ce08518b76f28cbf303a18b6b8700cfb0fcfa1f338f7fc56b6"