spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ws_service"
    username: "mslim"
    password: "{cipher}1604fa8b8a1d0565c0365f6ef704a024fa509ba7463954c9880dcee4f913a401"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update