spring:
  datasource:
    url: "jdbc:mariadb://database:3306/ws_service"
    username: "root"
    password: "{cipher}b1ca94ba056d855a62c355d9d52c4710bca29fe09bfc563d7d273467b81182ff"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update