spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/ws_service"
    username: "mslim"
    password: "{cipher}3700928ddb24c026683c547c4603f3e43dd4ecea80cf0bec30cc99208d99d743"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update