spring:
  datasource:
    url: "jdbc:mariadb://database:3306/ws_service"
    username: "root"
    password: "{cipher}da3d43d6400830596781a2669c14d192863d57b804c10c62a1ff5699cac681e6"
    dbcp2:
      test-while-idle: true  
      validation-query: "SELECT 1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true   
    hibernate:
      ddl-auto: update